# Netlify Configuration File

# This is the single most important rule.
# It tells Netlify how to handle the admin page.
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true # This is the key! It ensures this rule always wins.

# These are your existing rules for clean URLs.
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/database"
  to = "/database.html"
  status = 200

[[redirects]]
  from = "/intelligence"
  to = "/intelligence.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

# These are your existing rules for detail pages.
[[redirects]]
  from = "/models/:id"
  to = "/model-detail.html?id=:id"
  status = 200

[[redirects]]
  from = "/intelligence/:id"
  to = "/intelligence-detail.html?id=:id"
  status = 200

# This is the CORS header rule we added before.
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"